### ISSUE TITLE
更换对话框头部布局后报错

### ISSUE THREAD

**Issue by Saxxhw** [saiwu-bigkoo/Android-PickerView#31]
您好，我想在项目中使用您的这个库，不过对话框的头部样式不是很合适，所以想自己更换一个布局，去掉了取消按钮，运行之后一直报错。
java.lang.NoSuchFieldError: No static field btnSubmit of type I in class Lcom/bigkoo/pickerview/R$id; or its superclasses (declaration of 'com.bigkoo.pickerview.R$id' appears in /data/app/com.rdwl.rql-1/base.apk)
                                                                  at com.bigkoo.pickerview.TimePickerView.<init>(TimePickerView.java:34)
                                                                  at com.rdwl.rql.company.activities.InformInterviewAty.init(InformInterviewAty.java:77)
                                                                  at com.saxxhw.lib.base.BaseActivity.onCreate(BaseActivity.java:50)
                                                                  at com.rdwl.rql.base.RqlBaseAty.onCreate(RqlBaseAty.java:38)
                                                                  at android.app.Activity.performCreate(Activity.java:6142)
                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1115)
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2514)
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2642)
                                                                  at android.app.ActivityThread.access$800(ActivityThread.java:177)
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1511)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                  at android.os.Looper.loop(Looper.java:194)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5670)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:972)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
请问这是什么错误？

**Comment by saiwu-bigkoo** [comment]
你应该是没有删除干净吧，xml删了，代码里面也删了吗？

**Comment by saiwu-bigkoo** [comment]
这个提示是 确定按钮的问题，你检查下是不是删错
