### ISSUE TITLE
点空白处报ClassCastException

### ISSUE THREAD

**Issue by iwgang** [saiwu-bigkoo/Android-PickerView#36]
如点年份上面的空白处，其它如月、日...也会

*代码
```
 final TimePickerView pvTime = new TimePickerView(this, TimePickerView.Type.ALL);
        //控制时间范围
        Calendar calendar = Calendar.getInstance();
        pvTime.setRange(calendar.get(Calendar.YEAR), calendar.get(Calendar.YEAR)+1);
        pvTime.setTime(new Date());
        pvTime.setCyclic(false);
        pvTime.setCancelable(true);
        //时间选择后回调
        pvTime.setOnTimeSelectListener(new TimePickerView.OnTimeSelectListener() {
            @Override
            public void onTimeSelect(Date date) {
                Log.i("wg", new SimpleDateFormat("yyyy-MM-dd HH:mm").format(date));
            }
        });
        findViewById(R.id.btn_selTime).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                pvTime.show();
            }
        });
```

*错误信息
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
                                                                     at com.bigkoo.pickerview.adapter.NumericWheelAdapter.indexOf(NumericWheelAdapter.java:52)
                                                                     at com.bigkoo.pickerview.lib.WheelView.onDraw(WheelView.java:413)
                                                                     at android.view.View.draw(View.java:15255)
                                                                     at android.view.View.buildDrawingCacheImpl(View.java:14501)
                                                                     at android.view.View.buildDrawingCache(View.java:14363)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:14172)
                                                                     at android.view.View.getDisplayList(View.java:14213)
                                                                     at android.view.View.draw(View.java:14983)
                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
                                                                     at android.view.View.draw(View.java:15258)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:14191)
                                                                     at android.view.View.getDisplayList(View.java:14213)
                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:14151)
                                                                     at android.view.View.getDisplayList(View.java:14213)
                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:14151)
                                                                     at android.view.View.getDisplayList(View.java:14213)
                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:14151)
                                                                     at android.view.View.getDisplayList(View.java:14213)
                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:14151)
                                                                     at android.view.View.getDisplayList(View.java:14213)
                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:14151)
                                                                     at android.view.View.getDisplayList(View.java:14213)
                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:14151)
                                                                     at android.view.View.getDisplayList(View.java:14213)
                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:14151)
                                                                     at android.view.View.getDisplayList(View.java:14213)
                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:14151)
                                                                     at android.view.View.getDisplayList(View.java:14213)
                                                                     at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:276)
                                                                     at 
android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:282)
                                                                     at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:317)
                                                                     at android.view.ViewRootImpl.draw(ViewRootImpl.java:2541)
                                                                     at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2354)
                                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1984)
                                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1062)
                                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5911)
                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:787)
                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:600)
                                                                     at android.view.Choreographer.doFrame(Choreographer.java:570)
                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:773)
                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                 	at android.app.ActivityThread.main(

**Comment by saiwu-bigkoo** [comment]
请问你使用的版本是？

**Comment by iwgang** [comment]
compile 'com.bigkoo:pickerview:2.0.5'

**Comment by saiwu-bigkoo** [comment]
谢谢你的反馈，2.0.6修复了这个问题，请升级
