### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by lpslpsl** [saiwu-bigkoo/Android-PickerView#55]
使用的时候遇到   java.lang.ArrayIndexOutOfBoundsException: length=454; index=-1
                                                                     at java.util.ArrayList.get(ArrayList.java:310)
                                                                     at com.bigkoo.pickerview.view.WheelOptions$2.onItemSelected(WheelOptions.java:118)
                                                                     at com.bigkoo.pickerview.view.WheelOptions$1.onItemSelected(WheelOptions.java:104)
                                                                     at com.bigkoo.pickerview.lib.OnItemSelectedRunnable.run(OnItemSelectedRunnable.java:12)
                                                                     at android.os.Handler.handleCallback(Handler.java:733)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:136)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5045)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                     at dalvik.system.NativeStart.main(Native Method)
，还有一点疑问。因为这个控件在使用的时候是要先把所有数据填充进去。总共那么多城市区县。我读取数据的时候都读了十几二十秒才做成需要的格式传进去，这样实在是很慢，能不能动态的跟据选择的省份再去加载它自己的对应的城市和区县数据。数据存在本地读取其实还是挺快的不会影响体验。

**Comment by saiwu-bigkoo** [comment]
这个需要自己用基控件进行定制了

**Comment by lpslpsl** [comment]
好的吧
